version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"            # tu app: http://localhost:8080
    volumes:
      - ./:/var/www/html     # montamos tu código local en el contenedor
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: tareas_db
      DB_USER: tareauser
      DB_PASS: tareapass

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tareas_db
      MYSQL_USER: tareauser
      MYSQL_PASSWORD: tareapass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # opcional para inicializar la BD
    ports:
      - "3309:3309"  # opcional si quieres conectarte desde host (Hecho para desarrollo)

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"     # phpMyAdmin: http://localhost:8081

volumes:
  db_data:
