CREATE DATABASE IF NOT EXISTS tareas_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tareas_db;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  detalles TEXT,
  fecha DATE NOT NULL,
  completada TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
